### ISSUE TITLE
Parsing error loading recipe inca:spit_decay_leather_pants

### ISSUE THREAD

**Issue by calloatti** [tyra314/Inca#9]
MC 1.15.2
inca-1.1.1.jar

```
[05:24:50] [Server thread/ERROR]: Parsing error loading recipe inca:spit_decay_leather_pants
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:leather_pants'
	at net.minecraft.class_1856.method_17873(class_1856.java:162) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_252]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[intermediary-minecraft-1.15.2-client.jar:?]
```

**Comment by tyra314** [comment]
I'm could swear I checked all recipes and they were working 🤦

**Comment by tyra314** [comment]
Oh I see it now. That recipe is a duplicate with wrong ids. You can ignore the error.
